version: '2'

services:

    #### PostgreSQL
    postgres:
        image: postgres
        environment:
            - "POSTGRES_USER=taiga"
            - "POSTGRES_PASSWORD=taiga"
            - "POSTGRES_DB=taiga"
        volumes:
            - ./taiga-db:/var/lib/postgresql/data
# Local port for debuging purpose
#        ports:
#            - "54321:5432"

    #### Taiga Backend
    taiga-back-base:
        build: backend
        volumes:
            - ./backend/settings.py:/taiga/settings/local.py:ro
        environment:
            - "API_NAME:localhost"

    taiga-back:
        extends: taiga-back-base
        volumes:
            - ./taiga-static:/taiga/static
            - ./taiga-media:/taiga/media
        ports:
            - "8000:8000"

    taiga-init:
        extends: taiga-back-base
        command: "./db_init.sh"

    taiga-demo-data:
        extends: taiga-back-base
        command: "python3 manage.py sample_data"

    #### Taiga Frontend
    taiga-front:
        build: frontend
        environment:
            - "API_NAME:taiga-back"
        volumes:
            - ./frontend/nginx-default-vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/conf.json:/taiga/conf.json:ro
        volumes_from:
            - taiga-back
        ports:
            - "80:80"
