version: '2'

services:

    postgres:
        image: postgres
        environment:
            - "POSTGRES_USER=taiga"
            - "POSTGRES_PASSWORD=taiga"
            - "POSTGRES_DB=taiga"
        volumes:
            - /tmp/taiga_data:/var/lib/postgresql/data
# Local port for debuging purpose
#        ports:
#            - "54321:5432"

    taiga-back:
        build: backend
        environment:
            - "API_NAME:localhost"
        ports:
            - "8000:8000"

    taiga-init:
        build: backend
        environment:
            - "API_NAME:localhost"
        command: "./db_init.sh"

    taiga-demo-data:
        build: backend
        environment:
            - "API_NAME:localhost"
        command: "python3 manage.py sample_data"

    taiga-front:
        build: frontend
        environment:
            - "API_NAME:taiga-back"
        volumes:
            - ./frontend/nginx-default-vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/conf.json:/taiga/conf.json:ro
        volumes_from:
            - taiga-back
        ports:
            - "80:80"
